# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    command: ['start-dev --health-enabled=true --spi-theme-default=soi --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --import-realm']
    volumes:
      - ../resources/theme:/opt/keycloak/themes
      - ../realm-config:/opt/keycloak/data/import
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KC_SPI_THEME_DEFAULT=soi
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9443:9443
    healthcheck:
      test: ["CMD-SHELL", " curl --head http://localhost:9080/health/ready | grep -q '200 OK' "]